baseURL = "http://uk960214.github.io/"
languageCode = "en-us"
title = "Koowoy Devs"
theme = "mainroad"
paginate = "10"
googleAnalytics = "G-KJHZ868TNQ"

[Author]
  name = "Koowoy"
  
[Params]
  description = "Koowoy Develops Yet Again Today" # Site description. Used in meta description
  copyright = "Koowoy" # Footer copyright holder, otherwise will use site title
  readmore = true # Show "Read more" button in list if true
  pager = true # Show pager navigation (prev/next links) at the bottom of pages if true
  post_meta = ["author", "date", "categories"] # Order of post meta information
  dateformat = "2006-01-02" # Change the format of dates

[Params.logo]
  title = "Koowoy Devs" # Logo title, otherwise will use site title
  subtitle = "Koowoy Develops Yet Again Today" # Logo subtitle

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "left"  # Configure layout for list pages
  single = false # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["categories", "recent", "search", "taglist", "social"]

[Params.widgets]
  recent_num = 3 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget

[Params.widgets.social]
  # Enable parts of social widget
  instagram = "valenti700"
  github = "uk960214"

[taxonomies]
  category = "categories"
  tag = "tags"